mySelf = ['Rahmat', '31', 'graduate', 'cse', 'Muslim']
num = [4, 6, 9, 2, 4, 5, 9, 4, 17, 56, 23, 16]

# print(mySelf)
# print(mySelf[0])
# print(mySelf[4])
# print(mySelf[2:])
# print(mySelf[-1])
# print('amma' in mySelf)
# print(mySelf + ['amma', 'abba'])
# print(len(mySelf))
# mySelf.append('bhaiya')
# print(mySelf)
# mySelf.insert(2,"bhabi")
# print(mySelf)
# mySelf.sort()
# print(mySelf)
num.sort()
print(num)
num.pop()
print(num)
# num.clear()
# print(num)
c = num.count(4)
print(c)
